const actionTypes = {
    HOST_INIT: "HOST_INIT",
    HOST_START: "HOST_START",
    HOST_END: "HOST_END",
    HOST_ADD: "HOST_ADD",

    USER_INIT: "USER_INIT",
    USER_START: "USER_START",
    USER_END: "USER_END",
    USER_ADD: "USER_ADD",
    USER_SCORE: "USER_SCORE",
    USER_LOSE: "USER_LOSE",

    GAME_INIT: "GAME_INIT",
    GAME_START: "GAME_START",
    GAME_OVER: "GAME_OVER",
}

export default actionTypes
